Kind E2E testing using KinD
k8snetworkplumbingwg/sriov-network-operator pull request #100
Opened 2021-04-04 18:54 UTC by martinkennelly

Add option to execute E2E tests using KinD

    * Golang code to ensure VFs created during testing remain
      in test network namespace (KinD worker network namespace)

    * Shell script to fetch test tools, execute E2E tests using
      KinD and teardown KinD test environment

Depends on unmerged #97

2021-04-06 16:14 UTC, mrostecki commented
I tried to test this PR (by checking out directly your branch), but unfortunately I'm getting those errors:

https://paste.opensuse.org/85826568

Any idea what I'm doing wrong? I'm running those with `./hack/test-e2e-kind-cluster.sh 0000:81:00.1` and my devices are:

```
# lshw -c network -businfo  
Bus info          Device     Class          Description
=======================================================
pci@0000:02:00.0  eth0       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:02:00.1  eth1       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:81:00.0  eth2       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:81:00.1  eth3       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:81:00.2  eth4       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:81:00.3  eth5       network        Ethernet Controller X710 for 10GbE SFP+
pci@0000:81:0a.0  eth13      network        Ethernet Virtual Function 700 Series
pci@0000:81:0a.1  eth12      network        Ethernet Virtual Function 700 Series
pci@0000:81:0a.2  eth11      network        Ethernet Virtual Function 700 Series
pci@0000:81:0a.3  eth10      network        Ethernet Virtual Function 700 Series
```

2021-04-07 16:27 UTC, martinkennelly commented
@mrostecki I have a feeling it is issue with KinD cluster or connectivity to the KinD cluster. Catch me on NPWG slack tomorrow and we can have a look. I sent you an email with slack contact details. I have seen this error when the test cases were unable to connect to KinD cluster so I added this command to the script:

```
export KUBECONFIG="${HOME}/.kube/config"
```

2021-04-14 09:47 UTC, martinkennelly commented
I am going to rework this patch to remove calling the pf network namespace setting from being called in the shell script to adding it into the test script itself. Thanks for feedback @mrostecki ! Hoping for more!

2021-04-14 09:51 UTC, mrostecki requested changes

2021-04-14 09:51 UTC, mrostecki commented on hack/test-e2e-kind-cluster.sh
> +"${root}hack/pf-vf-netns-set" --pfpciaddress "${test_pf_pci_addr}" --netnspath "${netnspath}" &
I'd suggest doing it with `sudo -E` if the script is launched by an user.

2021-04-23 15:46 UTC, martinkennelly commented
@mrostecki can you retest it? See the file ```docs/test-kind.md```

2021-04-26 14:32 UTC, mrostecki approved these changes
Thanks! New changes LGTM and they work without any additional changes

```
Ran 5 of 5 Specs in 531.699 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSriovTests (531.70s)
PASS
coverage: [no statements]
ok      github.com/k8snetworkplumbingwg/sriov-network-operator/test/e2e 531.723s        coverage: [no statements]
make: Leaving directory '/home/agabus/sriov-network-operator'
```

2021-05-12 05:27 UTC, pliurh commented
@martinkennelly could you rebase this PR.

If I understand it correctly, we still need a machine with an SRIOV NIC to run this test, right?

2021-05-25 11:47 UTC, martinkennelly commented
@pliurh Done. I made one change following rebase captured in the head commit https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/100/commits/f116730387284e09f1bd57f97a42fc3423be29a5 to disable the webhooks explicitly when testing E2E - a change enabled webhooks by default now. I think they should be enabled when we have sufficient tests for them.

2021-06-15 07:33 UTC, merged