Add Intel E810 PF 1591 Network Adapter
k8snetworkplumbingwg/sriov-network-operator pull request #326
Opened 2022-06-22 17:44 UTC by novacain1

The Intel series of E810 cards with a 1591 PF ID need to be added to the supported card listing in OpenShift.  This PCI ID belongs to [Intel.](https://www.pcilookup.com/?ven=8086&dev=1591&action=submit)

Cards have Vendor ID 8086, PF 1591, and VF of 1889.

Note: Silicom TimeSync cards (STS2, STS4, etc) contain this embedded E810 in those particular network adapters.

Cards were tested internally in Red Hat and found to be passing.  Request of this PR is to get them to the supported list of devices.

2022-06-23 08:37 UTC, e0ne requested changes
@novacain1  thanks for your contributions. Please follow this https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/supported-hardware.md guideline to add new supported hardware. Alse, please rebase your PR to not include merge commit

2022-06-23 08:59 UTC, SchSeba commented
/cc @Eoghan1232

2022-06-24 13:58 UTC, Eoghan1232 commented on deploy/configmap.yaml
> +  Intel_ice_Silicom_E810: "8086 1591 1889"
```suggestion
 Intel_ice_Columbiaville_E810: "8086 1591 1889"
```

2022-06-24 13:58 UTC, Eoghan1232 commented on deployment/sriov-network-operator/templates/configmap.yaml
> +  Intel_ice_Silicom_E810: "8086 1591 1889"
same as above.

2022-06-24 13:59 UTC, Eoghan1232 commented
just added a comment, name change.
Otherwise LGTM.

Please also update the supported-hardware ReadMe.
https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/supported-hardware.md

2022-06-27 08:54 UTC, SchSeba commented
/lgtm

2022-06-27 08:55 UTC, Eoghan1232 approved these changes

2022-06-27 10:50 UTC, adrianchiris commented
lets squash to single commit and update commit message like @e0ne  suggested. then i think we are good 2 go

2022-06-27 17:01 UTC, adrianchiris approved these changes

2022-06-27 17:05 UTC, merged