config-daemon: fix NM udev path
k8snetworkplumbingwg/sriov-network-operator pull request #369
Opened 2022-10-10 13:56 UTC by zeeke

Function `tryCreateNMUdevRule()` was wrongly
concatenating path components, as `path.Join(...)`
removes every trailing slashes to the output string.

Adding unit tests on that func,

Signed-off-by: Andrea Panattoni <apanatto@redhat.com>

2022-10-10 15:11 UTC, eoghanlawless requested changes

2022-10-10 15:11 UTC, eoghanlawless commented on pkg/daemon/daemon_test.go
> +			}, "10s").WithOffset(1).Should(Equal(expectedContents))
```suggestion
			assertFileContents(networkManagerUdevRulePath, expectedContents)
```

2022-10-10 17:13 UTC, eoghanlawless approved these changes
LGTM

2022-10-13 08:01 UTC, cgoncalves commented
LGTM

2022-10-13 13:52 UTC, e0ne approved these changes

2022-10-13 13:52 UTC, merged