Don't start config daemon on unsupported platforms
k8snetworkplumbingwg/sriov-network-operator pull request #456
Opened 2023-06-12 18:01 UTC by EmilienM

The operator is only supported on Baremetal and OpenStack.
We should not start the config daemon elsewhere, as this is not
something we have tested.

On platform-agnostic deployments, there are a few unknowns that could
potentially be problematic especially for when running in virtualized
environments outside of the OpenStack platform type.

2023-06-13 08:58 UTC, SchSeba commented
/hold
please wait with this PR

2023-06-19 14:06 UTC, SchSeba commented
This is not always the case for example I deploy a kubernetes cluster with kubeadm on a baremetal node and it doesn't contain the providerID but everything still work as expected.
With this PR the operator will only run on platform that got deployed via supported provider like OpenStack or Metal3.

Instead I think the deamon should not do anything on the system if there are no policies on it. for example not try to configure Udev rules.

2023-07-05 06:12 UTC, e0ne commented
> This is not always the case for example I deploy a kubernetes cluster with kubeadm on a baremetal node and it doesn't contain the providerID but everything still work as expected. With this PR the operator will only run on platform that got deployed via supported provider like OpenStack or Metal3.
> 
> Instead I think the deamon should not do anything on the system if there are no policies on it. for example not try to configure Udev rules.

I agree with @SchSeba. This patch breaks current support of vanilla k8s

2023-07-05 06:15 UTC, e0ne requested changes

2023-07-05 06:15 UTC, e0ne commented on cmd/sriov-network-config-daemon/start.go
> +	if platformType != utils.Baremetal && platformType != utils.VirtualOpenStack {
This should be re-visited, because Baremetal is our defaults and this statement will be always True

2023-10-30 13:18 UTC, closed without merging