Update Webhook
k8snetworkplumbingwg/sriov-network-operator pull request #624
Opened 2024-02-06 17:48 UTC by adrianchiris

As the operator no longer creates default
SriovOperatorConfig and SriovNetworkNodePolicy
the webhook is updated in the following Manner:

Validating:
- Allow deletion of default config/policy.
- Block create/update of non default config CR

Mutating:
- keep skipping default but add a comment to mark as deprecated.

2024-02-06 17:49 UTC, adrianchiris commented
Related to #592

2024-02-07 17:13 UTC, e0ne requested changes

2024-02-07 17:13 UTC, e0ne commented on pkg/webhook/validate.go
> +	if operation == v1.Delete {
I would like to get more feedback here: from one side, it should be OK to re-create default policy, from other, I would like to allow only update once we've got default policy to not introduce possible race conditions and unnecessary reconcile loops.

I'll press `Request changes` button just to get more attention to this from other maintainers, feel free to ignore my vote

2024-02-07 19:44 UTC, e0ne approved these changes

2024-02-20 11:43 UTC, ykulazhenkov approved these changes

2024-02-22 07:47 UTC, adrianchiris commented
@zeeke @SchSeba could you take a quick look at this one ?  the last of the series :)

2024-02-22 10:07 UTC, merged